### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by crapthings** [Hank-Tsou/Template-Matching#2]
python3 Template_Matching.py -i 1.jpg -t 2.jpg

hello i've changed to another image but failed with these message

```
Traceback (most recent call last):
  File "Template_Matching.py", line 69, in <module>
    top_left = template_matching(image, target)
  File "Template_Matching.py", line 36, in template_matching
    NccValue = np.zeros((height-tar_height, width-tar_width))
ValueError: negative dimensions are not allowed
```

**Comment by crapthings** [comment]
![1](https://user-images.githubusercontent.com/1147704/97298392-4fe89f80-188e-11eb-9011-13d30dbdbfd1.jpg)
![2](https://user-images.githubusercontent.com/1147704/97298396-51b26300-188e-11eb-8e21-b7921ab0b160.jpg)

**Comment by crapthings** [comment]
okay i think order is wrong

python3 Template_Matching.py -i 2.jpg -t 1.jpg works

but its kinda slow even i reduce image size to 30%
